import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Loader from "@/components/common/loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ELS - Landing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Loader />
        {children}
      </body>
    </html>
  );
}
